name: mtag # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Work. Tag. Report. Repeat.
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
apps:
  mtag:
    command: bin/start_mtag
parts:
  mtag:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    #override-build: |
    #  snapcraftctl build
    #  pip3 install wheel
    #  pip3 install pycairo
    #  pip3 install PyGObject
    build-packages: [python3-wheel, libgirepository1.0-dev, gcc, libcairo2-dev, pkg-config, python3-dev, gir1.2-gtk-3.0]
    stage-packages: [libgirepository1.0-dev, libcairo2-dev, pkg-config, python3-dev, gir1.2-gtk-3.0]
    python-packages:
      - wheel
      - pycairo
      - PyGObject
